export const URL_SAVEDATA = '/api/savedata'
export const URL_PASTWEEKEXPENSES = '/api/pastweekexpenses'
export const URL_MONTHLYPERCENTAGEBREAKDOWN = '/api/monthlypercentagebreakdown'
export const URL_DAILYEXPENSES = '/api/dailyexpenses'
export const URL_MONTHLYEXPENSES = '/api/monthlyexpenses'
export const URL_SUMMARY = '/api/summary'
export const URL_ACTIONFILTER = '/api/actionfilter'
export const URL_SEARCH = '/api/search'
export const URL_USER = '/api/users'

export const URL_EXPENSES_TODAY = '/api/expenses/today'
export const URL_EXPENSES_MONTH = '/api/expenses/month'
export const URL_EXPENSES_MONTHLY_BREAKDOWN = '/api/expenses/monthly-breakdown'
export const URL_WALLET_BUDGET = '/api/wallet-budget'
export const URL_CATEGORIES = '/api/categories'
