-- Full schema: tables, trigger fn, timezone helper, views.
-- Idempotent enough to run in a fresh Supabase project.
-- Run this FIRST. Then run 002_rpc_functions.sql.

--------------------------------------------------------------------------------
-- Shared: updated_on trigger function
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_on()
RETURNS trigger AS $$
BEGIN
  NEW.updated_on = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

--------------------------------------------------------------------------------
-- App-wide "today" in Asia/Manila (see project memory)
--------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION app_today()
RETURNS date
LANGUAGE sql STABLE AS $$
  SELECT (now() AT TIME ZONE 'Asia/Manila')::date;
$$;

--------------------------------------------------------------------------------
-- Tables (drop in dependency-safe order)
--------------------------------------------------------------------------------
DROP TABLE IF EXISTS expenses      CASCADE;
DROP TABLE IF EXISTS categories    CASCADE;
DROP TABLE IF EXISTS wallet_budget CASCADE;
DROP TABLE IF EXISTS users         CASCADE;
DROP TABLE IF EXISTS months        CASCADE;

CREATE TABLE categories (
  "ID"         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "imgPath"    varchar(255),
  sequence     integer,
  description  varchar(255),
  status       integer,
  created_on   timestamptz NOT NULL DEFAULT now(),
  updated_on   varchar(255)
);

CREATE TABLE expenses (
  "ID"         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "categoryID" bigint REFERENCES categories("ID"),
  description  varchar(100),
  amount       varchar(50),
  status       smallint NOT NULL DEFAULT 1,
  created_by   varchar(255),
  created_on   timestamptz NOT NULL DEFAULT now(),
  updated_on   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX expenses_categoryid_idx ON expenses("categoryID");
CREATE TRIGGER expenses_updated_on BEFORE UPDATE ON expenses
  FOR EACH ROW EXECUTE FUNCTION set_updated_on();

CREATE TABLE users (
  "ID"           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email          varchar(255),
  status         integer,
  created_on     timestamptz NOT NULL DEFAULT now(),
  updated_on     varchar(255),
  "colorThemeID" smallint NOT NULL DEFAULT 2
);

CREATE TABLE wallet_budget (
  "ID"        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       varchar(255),
  description varchar(255),
  amount      varchar(50),
  status      smallint NOT NULL DEFAULT 1,
  created_by  varchar(255),
  created_on  timestamptz NOT NULL DEFAULT now(),
  updated_on  timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER wallet_budget_updated_on BEFORE UPDATE ON wallet_budget
  FOR EACH ROW EXECUTE FUNCTION set_updated_on();

CREATE TABLE months (
  "ID"        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        varchar(255),
  description varchar(255),
  status      integer,
  created_on  timestamptz NOT NULL DEFAULT now(),
  updated_on  varchar(255)
);

--------------------------------------------------------------------------------
-- Views
--------------------------------------------------------------------------------
CREATE OR REPLACE VIEW expenses_view
WITH (security_invoker = true) AS
SELECT
  e."ID"          AS "ID",
  e."categoryID"  AS "categoryID",
  c."imgPath"     AS "imgPath",
  c.description   AS category,
  e.description   AS description,
  e.amount        AS amount,
  e.status        AS status,
  e.created_by    AS created_by,
  e.created_on    AS created_on,
  e.updated_on    AS updated_on
FROM expenses e
LEFT JOIN categories c ON e."categoryID" = c."ID"
WHERE e.status = 1;

CREATE OR REPLACE VIEW daily_expenses_view
WITH (security_invoker = true) AS
SELECT
  ROUND(SUM(e.amount::numeric), 2)                 AS amount,
  e.created_by,
  (e.created_on AT TIME ZONE 'Asia/Manila')::date  AS created_on
FROM expenses e
WHERE e.status = 1
GROUP BY (e.created_on AT TIME ZONE 'Asia/Manila')::date, e.created_by;

CREATE OR REPLACE VIEW monthly_expenses_view
WITH (security_invoker = true) AS
SELECT
  e.created_by                                                     AS "user",
  EXTRACT(MONTH FROM e.created_on AT TIME ZONE 'Asia/Manila')::int AS "monthID",
  m.code                                                           AS "monthCode",
  m.description                                                    AS month,
  EXTRACT(YEAR  FROM e.created_on AT TIME ZONE 'Asia/Manila')::int AS year,
  SUM(e.amount::numeric)                                           AS total
FROM expenses_view e
LEFT JOIN months m
  ON EXTRACT(MONTH FROM e.created_on AT TIME ZONE 'Asia/Manila')::int = m."ID"
WHERE e.status = 1
GROUP BY
  e.created_by,
  EXTRACT(MONTH FROM e.created_on AT TIME ZONE 'Asia/Manila'),
  EXTRACT(YEAR  FROM e.created_on AT TIME ZONE 'Asia/Manila'),
  m.code,
  m.description;

CREATE OR REPLACE VIEW today_expenses_view
WITH (security_invoker = true) AS
SELECT
  e."ID"          AS "ID",
  e."categoryID"  AS "categoryID",
  c.description   AS category,
  c."imgPath"     AS "imgPath",
  e.description   AS description,
  e.amount        AS amount,
  e.status        AS status,
  e.created_by    AS created_by,
  e.created_on    AS created_on,
  e.updated_on    AS updated_on
FROM expenses e
LEFT JOIN categories c ON e."categoryID" = c."ID"
WHERE (e.created_on AT TIME ZONE 'Asia/Manila')::date = app_today()
  AND e.status = 1;

CREATE OR REPLACE VIEW previous_expenses_view
WITH (security_invoker = true) AS
SELECT
  e."ID"                                                              AS "ID",
  e."categoryID"                                                      AS "categoryID",
  c."imgPath"                                                         AS "imgPath",
  c.description                                                       AS category,
  e.description                                                       AS description,
  e.amount                                                            AS amount,
  EXTRACT(MONTH FROM e.created_on AT TIME ZONE 'Asia/Manila')::int    AS "monthID",
  EXTRACT(YEAR  FROM e.created_on AT TIME ZONE 'Asia/Manila')::int    AS year,
  e.status                                                            AS status,
  e.created_by                                                        AS created_by,
  e.created_on                                                        AS created_on,
  e.updated_on                                                        AS updated_on
FROM expenses e
LEFT JOIN categories c ON e."categoryID" = c."ID"
WHERE (e.created_on AT TIME ZONE 'Asia/Manila')::date <> app_today()
  AND e.status = 1;
